# Generated by Django 2.0.3 on 2018-03-27 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='kunci1',
            field=models.CharField(default='DEFAULT VALUE', max_length=55),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='kunci2',
            field=models.CharField(default='DEFAULT VALUE', max_length=55),
            preserve_default=False,
        ),
    ]
