# Generated by Django 2.0.3 on 2018-03-27 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0002_auto_20180327_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='kunci1',
            field=models.CharField(default='test 123', max_length=55),
        ),
        migrations.AlterField(
            model_name='book',
            name='kunci2',
            field=models.CharField(default='test 456', max_length=55),
        ),
    ]
