# Generated by Django 2.0.3 on 2018-03-27 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0003_auto_20180327_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.AlterField(
            model_name='book',
            name='kunci1',
            field=models.CharField(default='test 123', max_length=55, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='kunci2',
            field=models.CharField(default='test 456', max_length=55, unique=True),
        ),
    ]
