# Generated by Django 2.0.3 on 2018-03-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0006_auto_20180327_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
