# Generated by Django 2.0.3 on 2018-03-29 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0014_auto_20180327_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speech', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(to='publishing.Author'),
        ),
        migrations.AddField(
            model_name='preface',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='publishing.Book'),
        ),
    ]
