# Generated by Django 2.0.3 on 2018-04-04 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishing', '0015_auto_20180329_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='foto',
            field=models.ImageField(default='pas_foto/default.jpg', upload_to='pas_foto'),
            preserve_default=False,
        ),
    ]
